import{S as m,o as y,F as v}from"./assets/subscription-809301f4.js";import{S as f}from"./assets/vendor-bb007519.js";const L="shop-storage",P=new m(L),h=document.querySelector(".cart-content-container"),S=document.querySelector(".empty-cart");l();function l(){P.getAllProducts().length?(h.classList.remove("is-hidden"),S.classList.add("is-hidden")):(h.classList.add("is-hidden"),S.classList.remove("is-hidden"))}function b(e){return e.map(({category:o,img:r,name:c,price:t,size:s,_id:d})=>`<li class="cart-item" data-id="${d}">
      <img class="cart-img-product" src="${r}" alt="${c}" />
      <div class="cart-product-description">
          <p class="cart-product-name">${c}</p>
          <p class="cart-product-text">Category: <span class="cart-text-black gap">${o}</span>  Size: <span class="cart-text-black">${s}</span></p>
          <p class="cart-product-price">$${t}</p>
      </div>
      <button type="button" class="cart-product-close-btn">
          <svg class="cart-icon-close">
              <use href="./icons.svg#icon-close"></use>
          </svg>
      </button>
  </li>`).join("")}let a=[];const A=document.querySelector(".number-of-product"),q=document.querySelector(".nav-span"),x=document.querySelector(".total-amount"),p=document.querySelector(".cart-list"),n=new m("shop-storage");p.addEventListener("click",I);const B=document.querySelector(".js-delete-all-btn");B.addEventListener("click",()=>{p.innerHTML="",n.removeAllProducts(),g(0),i(0),l()});function C(){a=n.getAllProducts()??[],p.innerHTML=b(a),g(a.length),i(a.reduce((o,r)=>o+r.price,0))}C();function g(e){A.textContent=e,q.textContent=e}function i(e){x.textContent=e.toFixed(2)}function I(e){if(!e.target.closest(".cart-product-close-btn"))return;const r=e.target.closest("li").dataset.id,c=n.getAllProducts().filter(t=>t._id!==r);n.setAllProduct(c),C(),i(c.reduce((t,s)=>t+s.price,0)),n.getAllProducts.length||l()}const u=new m("shop-storage"),$=new v,w=document.getElementById("subscription-form"),E=document.querySelector(".cart-list"),F=document.getElementById("email");w.addEventListener("submit",async e=>{e.preventDefault();const o=u.getAllProducts(),r=document.getElementById("email").value;if(o&&o.length>0){const c={email:r,products:o.map(t=>({productId:t._id,amount:1}))};try{const t=await $.placeOrder(c);if(t&&t.message){u.removeAllProducts(),y();const s=document.querySelector(".modal-success-title"),d=document.querySelector(".modal-success-message");s.textContent="Order success",d.textContent=t.message,E.innerHTML="",F.value="",i(0),g(u.getAllProducts().length),l()}}catch(t){f.fire({icon:"error",title:"Error",text:t.response.data.message,showConfirmButton:!0,confirmButtonColor:"#6D8434",showCancelButton:!1,customClass:{popup:"small-popup",title:"custom-title",icon:"custom-icon"}})}}else f.fire({icon:"error",title:"Error",text:"The cart is empty. Please add products to the cart!",showConfirmButton:!0,confirmButtonColor:"#6D8434",showCancelButton:!1,customClass:{popup:"small-popup",title:"custom-title",icon:"custom-icon"}})});
//# sourceMappingURL=commonHelpers.js.map
