import{S as m,o as y,F as v}from"./assets/subscription-9d976e1b.js";import{S as f}from"./assets/vendor-bb007519.js";const L="shop-storage",P=new m(L),h=document.querySelector(".cart-content-container"),S=document.querySelector(".empty-cart");l();function l(){P.getAllProducts().length?(h.classList.remove("is-hidden"),S.classList.add("is-hidden")):(h.classList.add("is-hidden"),S.classList.remove("is-hidden"))}function b(t){return t.map(({category:o,img:c,name:r,price:e,size:s,_id:u})=>`<li class="cart-item" data-id="${u}">
      <img class="cart-img-product" src="${c}" alt="${r}" />
      <div class="cart-product-description">
          <p class="cart-product-name">${r}</p>
          <p class="cart-product-text">Category: <span class="cart-text-black gap">${o}</span>  Size: <span class="cart-text-black">${s}</span></p>
          <p class="cart-product-price">$${e}</p>
      </div>
      <button type="button" class="cart-product-close-btn">
          <svg class="cart-icon-close">
              <use href="./icons.svg#icon-close"></use>
          </svg>
      </button>
  </li>`).join("")}let a=[];const x=document.querySelector(".number-of-product"),A=document.querySelector(".nav-span"),q=document.querySelector(".total-amount"),p=document.querySelector(".cart-list"),n=new m("shop-storage");p.addEventListener("click",I);const B=document.querySelector(".js-delete-all-btn");B.addEventListener("click",()=>{p.innerHTML="",n.removeAllProducts(),g(0),i(0),l()});function C(){a=n.getAllProducts()??[],p.innerHTML=b(a),g(a.length),i(a.reduce((o,c)=>o+c.price,0))}C();function g(t){x.textContent=t,A.textContent=t}function i(t){q.textContent=t.toFixed(2)}function I(t){if(!t.target.closest(".cart-product-close-btn"))return;const c=t.target.closest("li").dataset.id,r=n.getAllProducts().filter(e=>e._id!==c);n.setAllProduct(r),C(),i(r.reduce((e,s)=>e+s.price,0)),n.getAllProducts.length||l()}function $(t){const o="Order Success! ",c=t.indexOf(o);return c!==-1?t.slice(c+o.length):t}const d=new m("shop-storage"),w=new v,E=document.getElementById("subscription-form"),F=document.querySelector(".cart-list"),O=document.getElementById("email");E.addEventListener("submit",async t=>{t.preventDefault();const o=d.getAllProducts(),c=document.getElementById("email").value;if(o&&o.length>0){const r={email:c,products:o.map(e=>({productId:e._id,amount:1}))};try{const e=await w.placeOrder(r);if(e&&e.message){d.removeAllProducts(),y();const s=document.querySelector(".modal-success-title"),u=document.querySelector(".modal-success-message");s.textContent="Order success",u.textContent=$(e.message),F.innerHTML="",O.value="",i(0),g(d.getAllProducts().length),l()}}catch(e){f.fire({icon:"error",title:"Error",text:e.response.data.message,showConfirmButton:!0,confirmButtonColor:"#6D8434",showCancelButton:!1,customClass:{popup:"small-popup",title:"custom-title",icon:"custom-icon"}})}}else f.fire({icon:"error",title:"Error",text:"The cart is empty. Please add products to the cart!",showConfirmButton:!0,confirmButtonColor:"#6D8434",showCancelButton:!1,customClass:{popup:"small-popup",title:"custom-title",icon:"custom-icon"}})});
//# sourceMappingURL=commonHelpers.js.map
